name: GitLeaks

on:
  pull_request:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *" # Run once a day at 4 AM

jobs:
  scan:
    name: GitLeaks Scan
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history required for Gitleaks

      # 2️⃣ Run GitLeaks scan
      - name: Run GitLeaks
        uses: gitLeaks/gitLeaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GitHub_TOKEN }}          # GitHub token for scanning
          GITLEAKS_LICENSE: ${{ secrets.GitLeaks_LICENSE }} # Required for Organizations, not personal accounts
